<? php
echo '<!DOCTYPE html>';
echo '<html lang="en">';
echo '<head>';
echo '<meta charset="UTF-8">';
echo '<title>Página para pruebas</title>';
echo '<link rel="stylesheet" href="css/main.css">';
echo '</head>';
echo '<body>';
echo '<div id="main-container">';
echo '<section id="intro-container">';
echo '<div class="center-align">';
echo '<nav>';
echo '<div id="logo"><img src="img/logo.png" alt=""></div>';
echo '<div id="menu-lista">';
echo '<ul>';
echo '<li><a href="#about-section">Acerca de..</a></li>';
echo '<li><a href="#work">Proyectos</a></li>';
echo '<li><a href="#footer">Contacto</a></li>';
echo '</ul>';
echo '</div>';
echo '</nav>';
echo '';
echo '<div class="section-columns">';
echo '<div>';
echo '<h2 class="white">Sitio para pruebas de "Hacking"</h2>';
echo '<div class="btn-section">';
echo '<a href="#about-section" class="btn btn-white">Conoce más</a>';
echo '</div>';
echo '</div>';
echo '';
echo '<div id="image-bg">';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</section>';
echo '';
echo '<div class="rectangle bg-white skew-left"></div>';
echo '';
echo '<div class="section" id="about-section">';
echo '<div class="center-align">';
echo '<div class="section-columns">';
echo '<div>';
echo '<h2>Diseño.<br />Desarrollo.<br/>Inspiración.</h2>';
echo '';
echo '</div>';
echo '';
echo '<div id="bio">';
echo '<h3>Esta página será utilizada para <span>pruebas</span> del proyecto de Seguridad, <span>por el momento</span> <span>esto es </span> <span>todo </span> lo que hemos logrado.<span>El diseño web</span><span> puede</span><span> mejorarse.</span></h3>';
echo '';
echo '<p>El profesor que <span>dicta esta asignatura </span>es el <span>Mgtr. Leandro Espinoza Montenegro</span></p>';
echo '';
echo '<p>Fernando Lezcano <span>se encargó de </span> levantar la página web y pulicarla en el servidor <span>de Azure.</span><span> Erasmo Navarro</span> realizará las pruebas con Nikto  <span>y Golismero</span>';
echo '<span>Danniel Justavino</span> realizará las pruebas con Owasp.  <span>Eperamos poder reforzar la seguridad de este sitio.</span></p>';
echo '';
echo '';
echo '<div class="btn-section">';
echo '<a href="#work" class="btn btn-black">Ver proyectos sobresalientes</a>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '';
echo '<div class="rectangle bg-gray skew-right"></div>';
echo '';
echo '<div class="section bg-gray" id="work">';
echo '<div class="center-align">';
echo '<div class="section-columns" >';
echo '<div>';
echo '<h2 class="white">Posters.<br />Sitios Web.<br/>Tutoriales.</h2>';
echo '<div class="btn-section">';
echo '<a href="" class="btn btn-white">Ver proyectos sobresalientes</a>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '';
echo '<div class="section bg-gray" id="work02">';
echo '<div class="center-align">';
echo '<div class="section-columns" >';
echo '<div>';
echo '<h2 class="white">Opinión.<br />Impactante.<br/>Blog.</h2>';
echo '<div class="btn-section">';
echo '<a href="" class="btn btn-white">Ver Proyecto</a>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '';
echo '<div class="section bg-gray" id="work03">';
echo '<div class="center-align">';
echo '<div class="section-columns" >';
echo '<div>';
echo '<h2 class="white">Patrón<br />Diseño.<br/>Móvil.</h2>';
echo '<div class="btn-section">';
echo '<a href="" class="btn btn-white">Ver Proyecto</a>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '';
echo '<div class="section bg-gray" id="work04">';
echo '<div class="center-align">';
echo '<div class="section-columns" >';
echo '<div>';
echo '<h2 class="white">Innovación.<br />Fresco.<br/>Color.</h2>';
echo '<div class="btn-section">';
echo '<a href="" class="btn btn-white">Ver Proyecto</a>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '';
echo '<div class="rectangle bg-black skew-left"></div>';
echo '<div class="section bg-black" id="footer">';
echo '<div class="center-align">';
echo '<div class="section-columns" >';
echo '<div>';
echo '<h2 class="white">Sigamos en Contacto.</h2>';
echo '<div class="btn-section">';
echo '<a href="mailto: contacto@misitio.com" class="btn btn-white">Mándame un mensaje</a>';
echo '</div>';
echo '</div>';
echo '';
echo '<div>';
echo '<h3>Contáctame si quieres conocerme y saber cómo podemos colaborar en tu siguiente proyecto.</h3>';
echo '<p>También puedes estar conmigo por medio de las redes sociales, enterarte de mi más reciente trabajo y conocerme un poco más.</p>';
echo '';
echo '<div class="btn-section">';
echo '<a href="http://www.facebook.com/misitio/" class="btn btn-white">Facebook</a>';
echo '<a href="http://www.twitter.com/misitio/" class="btn btn-white">Twitter</a>';
echo '<a href="http://www.instagram.com/misitio/" class="btn btn-white">Instagram</a>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '';
echo '</div>';
echo '</body>';
echo '</html>';
echo '';
echo '';
echo '';
echo '';
echo '';
echo '';
echo '';
echo '';
?>